import os
import pandas as pd

# =============================================================================
# Setup and Configuration
# =============================================================================
PRJNAME = config.get("PRJNAME") 
if not PRJNAME:
    raise ValueError("ERROR: Specify PRJNAME via --config")

# Load project-specific configuration from the project directory
configfile: f"reads/{PRJNAME}/config.yaml"

# --- Mandatory Configuration Checks ---
if "REF" not in config or not isinstance(config["REF"], dict):
    raise ValueError("\n\n[CONFIGURATION ERROR]\nMissing 'REF' block structure in config.yaml!\n")

mandatory_ref_vars = {
    "SOURCE": "choose from ncbi or ensembl",
    "SPECIES": "Latin binomial name (e.g., saccharomyces_cerevisiae)",
    "ASSEMBLY": "Major assembly build designation (e.g., R64-2-1 or GRCh38)"
}

for var, description in mandatory_ref_vars.items():
    if not config["REF"].get(var):
        raise ValueError(
            f"\n\n[CONFIGURATION ERROR]\n"
            f"Variable 'REF -> {var}' is missing!\n"
            f"Description: {description}\n"
        )

# =============================================================================
# Unified Global Path & Context Variables
# =============================================================================
# REF block variables
ref_cfg  = config["REF"]
source   = ref_cfg["SOURCE"].lower()
species  = ref_cfg["SPECIES"].lower()
assembly = ref_cfg["ASSEMBLY"]
release  = ref_cfg.get("RELEASE", "")
acc = ref_cfg.get("ACC") or "GCF_000848505.1"

# Name variations for structural renaming rules
species_low = species.replace(" ", "_")
species_cap = species_low.capitalize()

# Path Roots
data_src = config.get("DATA_SOURCE", "SRA")
base_src = config.get("DATABASE_SOURCE", "snpeff").lower()

REFS_DIR = f"refs/{source}/{species_low}/{assembly}/{release}"
READS_DIR = f"reads/{PRJNAME}"
LOG_DIR = f"reads/{PRJNAME}/logs"
DATABASES_DIR = f"databases/{base_src}/{source}.{species}.{assembly}.{release}"

# Sample file patterns
cb_umi_suffix = config.get("CB_UMI_SUFFIX", "1")
cdna_suffix = config.get("CDNA_SUFFIX", "2")




# =============================================================================
# Helper Functions
# =============================================================================
def get_refs(wildcards):
    """
    Dynamically routes pipeline requirements to the isolated database path layout.
    """
    if source == "ensembl":
        return {
            "fasta": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.fa",
            "gff": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.gff3",
            "gtf": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.gtf",
            "fai": f"{REFS_DIR}/{species_cap}.{assembly}.{release}.fa.fai"
        }
    elif source == "ncbi":
        return {
            "fasta": f"{REFS_DIR}/{acc}.fa",
            "gff": f"{REFS_DIR}/{acc}.gff3",
            "gtf": f"{REFS_DIR}/{acc}.gtf",
            "fasta": f"{REFS_DIR}/{acc}.fa.fai"
        }
    else:
        raise ValueError(f"Unsupported REF_SOURCE target: {source}")


# =============================================================================
# scRNA-seq Helper Functions
# =============================================================================
def get_scrna_runinfo(wildcards):
    """
    Triggers the universal metadata checkpoint and returns the filtered 
    scRNA run accessions.
    """
    # 1. Trigger checkpoint
    checkpoints.fetch_sra_metadata.get(**wildcards)
    
    # 2. Read output generated by parse_scrna_metadata
    csv_path = f"{READS_DIR}/runinfo_scrna.csv"
    
    # Read filtered CSV and extract Run column
    df = pd.read_csv(csv_path) 
    return df['Run'].tolist()

def get_scrna_fastq_qc(wildcards):
    """Generates QC report targets, merge by multiqc and forces fastq trimming."""
    runs = get_scrna_runinfo(wildcards)
    
    fastq = expand("{rddir}/fastqs/{r}_{pair}.fastq.gz", 
                    rddir=READS_DIR, r=runs, pair=[1, 2])
    
  
    return fastq





# =============================================================================
# Include Modular Rule Files
# =============================================================================
include: "toolbox/get_refs.smk"
include: "toolbox/qc.smk" 
include: "toolbox/scrna_getdata.smk" 



# =============================================================================
# Terminal Rules
# =============================================================================
rule note:
    input:
    run:
        print("\n" + "="*50)
        print("THIS SNAKEFILE SERVES AS TERMINAL FOR BIOINFORMATIC TOOLBOX")
        print("Please specify a target rule:")
        print("  snakemake download_refs     - Download fa, gff3 and gtf files")
        print("  snakemake scrna_getdata     - Acquire scRNA-Seq dataset")
        print("  snakemake qc                - run QC")
        print("RNAseq Analysis")
        print("  snakemake rna_align         - Run RNA alignment")
        print("  snakemake rna_exp           - Run RNA expression analysis")
        print("  snakemake exp_tools_compare - (optional) Compare expression analysis tools deseq2 vs edger")
        print("  snakemake rna_report        - Evaluate expression data with pca, MA, p-value histagram and volcano plots,")
        print("                                generate csv for list of significantly different expressed genes")
        print("  snakemake rna_enrich        - Generate heatmap and perform functional enrichment study")
        print("  snakemake rna_all           - Gets samples and refs, run QC, rna align, exp, report and enrich")
        print("="*50 + "\n")

rule download_refs:
    """Utility run-target that safely maps upstream conversion assets."""
    input: 
        lambda wildcards: list(get_refs(wildcards).values())


rule qc:
    """QC for fastq files."""
    input:


# =============================================================================
# scRNA-Seq Analysis
# =============================================================================
rule scrna_runinfo:
    """Download runinfo.csv or create one from fastq files under reads/project_name"""
    input: get_scrna_runinfo

rule scrna_download_fq_qc:
    input: get_scrna_fastq_qc

rule scrna_align:
    """Align RNAseq reads using spliced aligner/ pseudo aligner and generate visualization tracks."""
    input:

rule rna_exp:
    """Perform expression analysis using DESeq2 or edgeR."""
    input:


rule rna_report:
    """
    Executes biological threshold filtering,model diagnostics, and global PCA variance plotting.
    """
    input:


rule rna_enrich:
    """
    Generate Heatmap and perform functional enrichment study.
    """
    input:

rule rna_all:
    """A shortcut to run a full course of RNAseq with qc, aligner, exp, report and enrich."""
    input:  



